name: Install_dependences

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [ Release ]
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    steps:
      - uses: actions/checkout@master

      # Print environment variables to simplify development and debugging
      - name: Environment Variables
        shell: bash
        run: env

      # ============
      # DEPENDENCIES
      # ============

      - name: Dependencies [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          github:
            - path: eigenteam/eigen-git-mirror
              ref: 3.3.7

      - name: Dependencies [macOS]
        if: matrix.os == 'macOS-latest'
        run: |
          brew ungrade
          brew install eigen

      - name: Dependencies [Ubuntu]
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install
