name: Linux / OXS build

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'


jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [ Debug, Release ]
        os: [ ubuntu-latest, macOS-latest ] #windows-latest,

    steps:
      - uses: actions/checkout@master

      # Print environment variables to simplify development and debugging
      - name: Environment Variables
        shell: bash
        run: env

      # ============
      # DEPENDENCIES
      # ============
      - name: Googletest installer
      # You may pin to the exact commit or the version.
      # uses: MarkusJx/googletest-installer@2dbed3d0a9dc19bebe3e36773185ab9c17664c8d
        uses: MarkusJx/googletest-installer@v1.1

      - name: Dependencies [Windows]
        if: matrix.os == 'windows-latest'
        run: |
          vcpkg install eigen3

      - name: Dependencies [macOS]
        if: matrix.os == 'macOS-latest'
        run: |
          brew install eigen doxygen graphviz
          # googletest  

      - name: Dependencies [Ubuntu]
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libeigen3-dev
          sudo apt-get install -y graphviz doxygen

      - name: Create Build Environment
          # Some projects don't allow in-source building, so create a separate build directory
          # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . 

      - name: Test
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute tests defined by the CMake configuration.
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest -C $BUILD_TYPE
